export const productRows = [
    {
      id: 1,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 2,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 3,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 4,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 5,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 6,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 7,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 8,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 9,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 10,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 11,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
    {
      id: 12,
      custormerName: "Sithum Ravishka",
      address: 'No: 42, Mathugama, Srilanka',
      contactNumber: '074-2833579',
      productName: "Lay's potatos chips",
      orderPrice: 'Rs.600.00',
    },
  ];